name: clickable-action-secret-sync

on:
  workflow_dispatch:
    inputs:
      repo_name:
        required: true
        type: string
        description: Format shoule be "org/reponame" eg - IMISSHER99/secrets_sync

jobs:
  sync-secrets:
    name: Trigger Sync Secrets
    runs-on: ubuntu-latest
    steps:
      - name: Secrets Sync Action
        uses: jpoehnelt/secrets-sync-action@v1.8.0
        env:
          POSTGRES_DB_URL: ${{ secrets.POSTGRES_DB_URL }}
          POSTGRES_DB_USERNAME: ${{ secrets.POSTGRES_DB_USERNAME }}
          POSTGRES_DB_SECRET: ${{ secrets.POSTGRES_DB_SECRET }}
          DB_KIND: ${{ secrets.DB_KIND }}
          DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_HUB_TOKEN: ${{ DOCKER_HUB_USERNAME }}
        with:
          SECRETS: |
            POSTGRES_DB_URL
            POSTGRES_DB_USERNAME
            POSTGRES_DB_SECRET
            DB_KIND
            DOCKER_HUB_USERNAME
            DOCKER_HUB_USERNAME
          REPOSITORIES: |
            ${{ github.event.inputs.repo_name }}
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          CONCURRENCY: 10

  
  
